version: '3.8'

services:
  web:
    build: .
    command: python scripts/monitor_jobs.py
    volumes:
      - .:/app
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A celery_tasks.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A celery_tasks.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
